In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()
아이리스 = pd.get_dummies(아이리스)

In [3]:
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [4]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [5]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [6]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0438 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0489 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0422 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0468 - accuracy: 0.9867
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0530 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0489 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0509 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0504 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0459 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0436 - accuracy: 0.9800


In [ ]:
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9888140e-01 1.1183745e-03 2.4645675e-07]
 [9.9582481e-01 4.1733850e-03 1.7714831e-06]
 [9.9800795e-01 1.9913290e-03 7.7067642e-07]
 [9.9429768e-01 5.6989775e-03 3.3249496e-06]
 [9.9906737e-01 9.3242346e-04 2.0726823e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
# weights & bias 출력
print(model.get_weights())

[array([[ 0.76539147,  0.18002376, -0.81839705],
       [ 2.397471  , -0.0082116 , -0.9199122 ],
       [-3.9857068 , -0.20518649,  0.8920358 ],
       [-3.0819938 , -1.5374883 ,  2.0295527 ]], dtype=float32), array([ 2.0153842,  1.0242603, -1.3625611], dtype=float32)]
