In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)
레모네이드.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [3]:
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
독립

온도
0  20
1  21
2  22
3  23
4  24
5  25

In [4]:
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [5]:
X = tf.keras.layers.Input(shape=[1]) #독립 shape에서 col
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='mse')

In [6]:
model.fit(독립,종속, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 2ms/step - loss: 870.5754
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 866.1841
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 863.0092
Epoch 4/10
1/1 [==============================] - 0s 1ms/step - loss: 860.3570
Epoch 5/10
1/1 [==============================] - 0s 1ms/step - loss: 858.0075
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 855.8579
Epoch 7/10
1/1 [==============================] - 0s 1ms/step - loss: 853.8516
Epoch 8/10
1/1 [==============================] - 0s 1ms/step - loss: 851.9531
Epoch 9/10
1/1 [==============================] - 0s 3ms/step - loss: 850.1385
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 848.3912


In [7]:
model.predict(독립)

array([[14.211231],
       [14.920928],
       [15.630625],
       [16.340322],
       [17.050018],
       [17.759716]], dtype=float32)

In [8]:
model.get_weights()

[array([[0.70969695]], dtype=float32), array([0.01729182], dtype=float32)]

In [12]:
model.fit(독립, 종속, epochs=1000, verbose=0)

In [13]:
model.fit(독립,종속,epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 1ms/step - loss: 0.0053
Epoch 2/10
1/1 [==============================] - 0s 1ms/step - loss: 0.0052
Epoch 3/10
1/1 [==============================] - 0s 2ms/step - loss: 0.0052
Epoch 4/10
1/1 [==============================] - 0s 3ms/step - loss: 0.0052
Epoch 5/10
1/1 [==============================] - 0s 2ms/step - loss: 0.0052
Epoch 6/10
1/1 [==============================] - 0s 2ms/step - loss: 0.0052
Epoch 7/10
1/1 [==============================] - 0s 2ms/step - loss: 0.0052
Epoch 8/10
1/1 [==============================] - 0s 2ms/step - loss: 0.0052
Epoch 9/10
1/1 [==============================] - 0s 2ms/step - loss: 0.0052
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 0.0052


In [14]:
model.predict(독립)

array([[40.098736],
       [42.056633],
       [44.014534],
       [45.97243 ],
       [47.930332],
       [49.88823 ]], dtype=float32)

In [15]:
model.get_weights()

[array([[1.9578992]], dtype=float32), array([0.94074863], dtype=float32)]

In [16]:
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
dataset = pd.read_csv(파일경로)
dataset.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [17]:
#onehotencoding
encoded = pd.get_dummies(dataset)
encoded.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [18]:
print(encoded.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [19]:
독립 = encoded[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = encoded[['품종_setosa', '품종_versicolor','품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [21]:
X = tf.keras.layers.Input(shape=[4]) #독립 shape에서 col
Y = tf.keras.layers.Dense(3, activation='softmax')(X) #종속 shape에서 col
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy') 

In [22]:
model.fit(독립, 종속, epochs=10000, verbose=0)

In [23]:
독립.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭
0   5.1  3.5    1.4   0.2
1   4.9  3.0    1.4   0.2
2   4.7  3.2    1.3   0.2
3   4.6  3.1    1.5   0.2
4   5.0  3.6    1.4   0.2

In [25]:
model.predict(독립)

array([[1.00000000e+00, 3.98572494e-11, 2.74017462e-24],
       [1.00000000e+00, 3.38512907e-09, 3.04989004e-21],
       [1.00000000e+00, 3.72753439e-10, 1.57431999e-22],
       [1.00000000e+00, 1.04386526e-08, 2.38835073e-20],
       [1.00000000e+00, 2.34493328e-11, 1.42038054e-24],
       [1.00000000e+00, 2.82254886e-10, 4.62591096e-23],
       [1.00000000e+00, 1.06011921e-09, 1.07404011e-21],
       [1.00000000e+00, 3.55085295e-10, 7.98627382e-23],
       [1.00000000e+00, 2.66749520e-08, 1.43850379e-19],
       [1.00000000e+00, 1.43632051e-09, 5.81243014e-22],
       [1.00000000e+00, 1.20787894e-11, 2.67050666e-25],
       [1.00000000e+00, 1.86113847e-09, 1.20651663e-21],
       [1.00000000e+00, 1.29504341e-09, 6.25238178e-22],
       [1.00000000e+00, 1.49700141e-10, 6.36213859e-23],
       [1.00000000e+00, 1.32288420e-14, 6.33173092e-30],
       [1.00000000e+00, 2.60469245e-13, 9.00408842e-28],
       [1.00000000e+00, 2.89104634e-12, 6.30143077e-26],
       [1.00000000e+00, 1.34531