In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("day.csv")
df

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0          1  01-01-2018       1   0     1        0        6           0   
1          2  02-01-2018       1   0     1        0        0           0   
2          3  03-01-2018       1   0     1        0        1           1   
3          4  04-01-2018       1   0     1        0        2           1   
4          5  05-01-2018       1   0     1        0        3           1   
..       ...         ...     ...  ..   ...      ...      ...         ...   
725      726  27-12-2019       1   1    12        0        4           1   
726      727  28-12-2019       1   1    12        0        5           1   
727      728  29-12-2019       1   1    12        0        6           0   
728      729  30-12-2019       1   1    12        0        0           0   
729      730  31-12-2019       1   1    12        0        1           1   

     weathersit       temp     atemp      hum  windspeed  casual  registered  \
0             2  14.110847  18.18125  80.5833  10.749882     331         654   
1             2  14.902598  17.68695  69.6087  16.652113     131         670   
2             1   8.050924   9.47025  43.7273  16.636703     120        1229   
3             1   8.200000  10.60610  59.0435  10.739832     108        1454   
4             1   9.305237  11.46350  43.6957  12.522300      82        1518   
..          ...        ...       ...      ...        ...     ...         ...   
725           2  10.420847  11.33210  65.2917  23.458911     247        1867   
726           2  10.386653  12.75230  59.0000  10.416557     644        2451   
727           2  10.386653  12.12000  75.2917   8.333661     159        1182   
728           1  10.489153  11.58500  48.3333  23.500518     364        1432   
729           2   8.849153  11.17435  57.7500  10.374682     439        2290   

      cnt  
0     985  
1     801  
2    1349  
3    1562  
4    1600  
..    ...  
725  2114  
726  3095  
727  1341  
728  1796  
729  2729  

[730 rows x 16 columns]

In [5]:
x_1 = df.iloc[:,2:3].dropna(axis=1)
x_1

season
0         1
1         1
2         1
3         1
4         1
..      ...
725       1
726       1
727       1
728       1
729       1

[730 rows x 1 columns]

In [6]:
x_2 = df.iloc[:,5:13].dropna(axis=1)
x_2

holiday  weekday  workingday  weathersit       temp     atemp      hum  \
0          0        6           0           2  14.110847  18.18125  80.5833   
1          0        0           0           2  14.902598  17.68695  69.6087   
2          0        1           1           1   8.050924   9.47025  43.7273   
3          0        2           1           1   8.200000  10.60610  59.0435   
4          0        3           1           1   9.305237  11.46350  43.6957   
..       ...      ...         ...         ...        ...       ...      ...   
725        0        4           1           2  10.420847  11.33210  65.2917   
726        0        5           1           2  10.386653  12.75230  59.0000   
727        0        6           0           2  10.386653  12.12000  75.2917   
728        0        0           0           1  10.489153  11.58500  48.3333   
729        0        1           1           2   8.849153  11.17435  57.7500   

     windspeed  
0    10.749882  
1    16.652113  
2    16.636703  
3    10.739832  
4    12.522300  
..         ...  
725  23.458911  
726  10.416557  
727   8.333661  
728  23.500518  
729  10.374682  

[730 rows x 8 columns]

In [7]:
x_3 = df.iloc[:,15:16].dropna(axis=1)
x_3

cnt
0     985
1     801
2    1349
3    1562
4    1600
..    ...
725  2114
726  3095
727  1341
728  1796
729  2729

[730 rows x 1 columns]

In [8]:
x = pd.concat([x_1,x_2,x_3], axis=1)
x

season  holiday  weekday  workingday  weathersit       temp     atemp  \
0         1        0        6           0           2  14.110847  18.18125   
1         1        0        0           0           2  14.902598  17.68695   
2         1        0        1           1           1   8.050924   9.47025   
3         1        0        2           1           1   8.200000  10.60610   
4         1        0        3           1           1   9.305237  11.46350   
..      ...      ...      ...         ...         ...        ...       ...   
725       1        0        4           1           2  10.420847  11.33210   
726       1        0        5           1           2  10.386653  12.75230   
727       1        0        6           0           2  10.386653  12.12000   
728       1        0        0           0           1  10.489153  11.58500   
729       1        0        1           1           2   8.849153  11.17435   

         hum  windspeed   cnt  
0    80.5833  10.749882   985  
1    69.6087  16.652113   801  
2    43.7273  16.636703  1349  
3    59.0435  10.739832  1562  
4    43.6957  12.522300  1600  
..       ...        ...   ...  
725  65.2917  23.458911  2114  
726  59.0000  10.416557  3095  
727  75.2917   8.333661  1341  
728  48.3333  23.500518  1796  
729  57.7500  10.374682  2729  

[730 rows x 10 columns]

In [9]:
x['cnt']

0       985
1       801
2      1349
3      1562
4      1600
       ... 
725    2114
726    3095
727    1341
728    1796
729    2729
Name: cnt, Length: 730, dtype: int64

In [10]:
from sklearn import preprocessing
x = x.drop(['cnt'], axis=1)
x = preprocessing.normalize(x)

* 다시 봐야함

In [11]:
x

array([[0.0118016 , 0.        , 0.07080958, ..., 0.21456777, 0.95101154,
        0.12686576],
       [0.01328902, 0.        , 0.        , ..., 0.23504217, 0.92503116,
        0.2212902 ],
       [0.02064002, 0.        , 0.02064002, ..., 0.19546618, 0.90253249,
        0.34338194],
       ...,
       [0.01287345, 0.        , 0.0772407 , ..., 0.15602621, 0.96926391,
        0.10728296],
       [0.01786108, 0.        , 0.        , ..., 0.20692064, 0.86328505,
        0.41974469],
       [0.01654561, 0.        , 0.01654561, ..., 0.18488648, 0.9555092 ,
        0.17165548]])

In [12]:
df = df.drop('instant', axis=1)
df = df.drop('dteday', axis=1)
df

season  yr  mnth  holiday  weekday  workingday  weathersit       temp  \
0         1   0     1        0        6           0           2  14.110847   
1         1   0     1        0        0           0           2  14.902598   
2         1   0     1        0        1           1           1   8.050924   
3         1   0     1        0        2           1           1   8.200000   
4         1   0     1        0        3           1           1   9.305237   
..      ...  ..   ...      ...      ...         ...         ...        ...   
725       1   1    12        0        4           1           2  10.420847   
726       1   1    12        0        5           1           2  10.386653   
727       1   1    12        0        6           0           2  10.386653   
728       1   1    12        0        0           0           1  10.489153   
729       1   1    12        0        1           1           2   8.849153   

        atemp      hum  windspeed  casual  registered   cnt  
0    18.18125  80.5833  10.749882     331         654   985  
1    17.68695  69.6087  16.652113     131         670   801  
2     9.47025  43.7273  16.636703     120        1229  1349  
3    10.60610  59.0435  10.739832     108        1454  1562  
4    11.46350  43.6957  12.522300      82        1518  1600  
..        ...      ...        ...     ...         ...   ...  
725  11.33210  65.2917  23.458911     247        1867  2114  
726  12.75230  59.0000  10.416557     644        2451  3095  
727  12.12000  75.2917   8.333661     159        1182  1341  
728  11.58500  48.3333  23.500518     364        1432  1796  
729  11.17435  57.7500  10.374682     439        2290  2729  

[730 rows x 14 columns]

In [13]:
y = df['cnt']
y

0       985
1       801
2      1349
3      1562
4      1600
       ... 
725    2114
726    3095
727    1341
728    1796
729    2729
Name: cnt, Length: 730, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=0)

In [15]:
x_train

array([[0.03965123, 0.        , 0.03965123, ..., 0.41679521, 0.7996331 ,
        0.2241383 ],
       [0.03184164, 0.        , 0.09552491, ..., 0.51612666, 0.6958719 ,
        0.1539102 ],
       [0.01909946, 0.        , 0.07639783, ..., 0.14408917, 0.89847092,
        0.38517875],
       ...,
       [0.03800592, 0.        , 0.07601184, ..., 0.38670262, 0.81923911,
        0.24070492],
       [0.0359324 , 0.        , 0.07186481, ..., 0.39887484, 0.83742504,
        0.11530101],
       [0.06832237, 0.        , 0.08540296, ..., 0.29652248, 0.89601879,
        0.19572095]])

In [16]:
x_test

array([[0.04054735, 0.        , 0.0810947 , ..., 0.4313312 , 0.79067329,
        0.18866565],
       [0.03719017, 0.        , 0.0495869 , ..., 0.42574752, 0.80733666,
        0.13222842],
       [0.01861469, 0.        , 0.11168816, ..., 0.23092643, 0.92840781,
        0.19700899],
       ...,
       [0.03770222, 0.        , 0.05026963, ..., 0.46453097, 0.74985574,
        0.23981719],
       [0.05279891, 0.        , 0.05279891, ..., 0.26790233, 0.92673044,
        0.12099846],
       [0.03472298, 0.        , 0.03472298, ..., 0.43221436, 0.81840108,
        0.08826281]])

In [17]:
y_train

235    5130
524    7498
12     1406
161    4966
556    7264
       ... 
707    3228
192    4258
629    8395
559    6969
684    5698
Name: cnt, Length: 511, dtype: int64

In [18]:
y_test

196    5923
187    4592
14     1248
31     1360
390    4075
       ... 
155    4906
391    3456
571    6861
306    3974
200    4332
Name: cnt, Length: 219, dtype: int64

In [19]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((511, 9), (219, 9), (511,), (219,))

In [21]:
#x_train.info()

In [22]:
#x_train.head()

In [23]:
#x_train.tail()

In [25]:
#x_train[['season']]

In [26]:
#x_train['season'].unique()

In [27]:
#x_train['season'].value_counts()

In [28]:
#x_train.head()

In [31]:
#df.isnull().sum()

In [30]:
x_train['yr'].value_counts()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [270]:
x_train.head()

season  holiday  weekday  workingday  weathersit       temp     atemp  \
235       3        0        3           1           1  27.606653  31.53460   
524       2        0        6           0           1  29.144153  32.41835   
12        1        0        4           1           1   6.765000   7.54415   
161       2        0        6           0           1  29.725000  33.90190   
556       3        0        3           1           1  29.383347  32.51355   

         hum  windspeed   cnt  
235  60.5000  16.958236  5130  
524  43.7083   9.667229  7498  
12   47.0417  20.167000  1406  
161  65.4583  10.374950  4966  
556  63.3333  10.166111  7264

In [271]:
x_train['holiday'].value_counts()

0    496
1     15
Name: holiday, dtype: int64

* 어엉?

In [272]:
x_train['weekday'].value_counts() #일 - 0 시작 
#실제 2018/1/1은 월요일이기 때문에 화 - 0이라고 생각했었음

3    79
6    74
1    74
2    73
4    72
5    70
0    69
Name: weekday, dtype: int64

In [273]:
x_train[['weekday']]

weekday
235        3
524        6
12         4
161        6
556        3
..       ...
707        0
192        2
629        6
559        6
684        5

[511 rows x 1 columns]

* 2018/1/1은 월요일인데 데이터에는 토요일인것 같다 이상하다

In [274]:
x_train.head()

season  holiday  weekday  workingday  weathersit       temp     atemp  \
235       3        0        3           1           1  27.606653  31.53460   
524       2        0        6           0           1  29.144153  32.41835   
12        1        0        4           1           1   6.765000   7.54415   
161       2        0        6           0           1  29.725000  33.90190   
556       3        0        3           1           1  29.383347  32.51355   

         hum  windspeed   cnt  
235  60.5000  16.958236  5130  
524  43.7083   9.667229  7498  
12   47.0417  20.167000  1406  
161  65.4583  10.374950  4966  
556  63.3333  10.166111  7264

In [275]:
x_train['workingday'].value_counts() #workingday = 주중이라고 가정하면
#2018/1/1은 토요일이 됨

1    353
0    158
Name: workingday, dtype: int64

In [276]:
#x_train[x_train['instant'] >= 12].head() # 0부터 일요일이라고 가정

KeyError: 'instant'

In [277]:
x_train['weathersit'].value_counts()

1    328
2    171
3     12
Name: weathersit, dtype: int64

In [278]:
x_train['temp'].value_counts()

17.937500    4
26.035000    4
29.144153    4
28.563347    4
10.899153    3
            ..
29.520000    1
15.990000    1
18.347500    1
11.958347    1
4.407500     1
Name: temp, Length: 391, dtype: int64

In [280]:
#x_train['casual'].value_counts()

* 어엉?

In [282]:
#x_train['registered'].value_counts()

In [283]:
x_train.head()

season  holiday  weekday  workingday  weathersit       temp     atemp  \
235       3        0        3           1           1  27.606653  31.53460   
524       2        0        6           0           1  29.144153  32.41835   
12        1        0        4           1           1   6.765000   7.54415   
161       2        0        6           0           1  29.725000  33.90190   
556       3        0        3           1           1  29.383347  32.51355   

         hum  windspeed   cnt  
235  60.5000  16.958236  5130  
524  43.7083   9.667229  7498  
12   47.0417  20.167000  1406  
161  65.4583  10.374950  4966  
556  63.3333  10.166111  7264

In [284]:
x_train['cnt'].value_counts()

5119    2
7534    2
6043    2
6536    2
5260    2
       ..
6825    1
7852    1
3624    1
6830    1
4097    1
Name: cnt, Length: 491, dtype: int64

In [285]:
x_train['season'].value_counts()

2    132
3    131
1    125
4    123
Name: season, dtype: int64

In [286]:
x_train.head()

season  holiday  weekday  workingday  weathersit       temp     atemp  \
235       3        0        3           1           1  27.606653  31.53460   
524       2        0        6           0           1  29.144153  32.41835   
12        1        0        4           1           1   6.765000   7.54415   
161       2        0        6           0           1  29.725000  33.90190   
556       3        0        3           1           1  29.383347  32.51355   

         hum  windspeed   cnt  
235  60.5000  16.958236  5130  
524  43.7083   9.667229  7498  
12   47.0417  20.167000  1406  
161  65.4583  10.374950  4966  
556  63.3333  10.166111  7264

In [287]:
x_train['holiday'].value_counts() #공휴일

0    496
1     15
Name: holiday, dtype: int64

* 독립 = 계절, 공휴일, 요일, 주중, 날씨, 온도, 공기온도, 습도, 풍속
* 종속 = cnt

In [288]:
#instant, yr, mnth, casual, registered 컬럼삭제

In [289]:
x_train.columns

Index(['season', 'holiday', 'weekday', 'workingday', 'weathersit', 'temp',
       'atemp', 'hum', 'windspeed', 'cnt'],
      dtype='object')

* 독립 = 계절, 공휴일, 요일, 주중, 날씨, 온도, 공기온도, 습도, 풍속
* 종속 = cnt

In [222]:
train_data = x_train.drop('cnt', axis=1)
target = x_train['cnt']

train_data.shape, target.shape

((584, 9), (584,))

In [223]:
target.head()

704    5375
565    5870
185    4665
269    4120
178    4648
Name: cnt, dtype: int64

In [224]:
train_data.head()

season  holiday  weekday  workingday  weathersit       temp     atemp  \
704       4        0        4           1           1  10.489153  12.91020   
565       3        0        5           1           2  27.299153  30.65125   
185       3        0        2           1           1  30.613347  34.81690   
269       4        0        2           1           2  26.103347  28.72625   
178       3        0        2           1           1  30.510847  34.62790   

         hum  windspeed  
704  50.8750  11.708518  
565  84.4167  14.000789  
185  59.0417   8.459286  
269  88.5417   7.917457  
178  63.4167   9.666961

## Modeling

* Linear Regression

In [307]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

In [308]:
linearRegressor = LinearRegression()

In [312]:
linearRegressor.fit(x_train, y_train)

LinearRegression()

In [313]:
y_pred = linearRegressor.predict(x_test)

In [2]:
y_pred

NameError: name 'y_pred' is not defined

In [316]:
mse = mean_squared_error(y_test, y_pred)
mse

1859726.764301108

In [318]:
r = r2_score(y_test, y_pred)
r

0.55668680309065

In [320]:
mae = mean_absolute_error(y_test, y_pred)
mae

1154.572857196566

* RandomForest

In [337]:
from sklearn.ensemble import RandomForestClassifier

In [339]:
Rf = RandomForestClassifier()
Rf.fit(x_train, y_train)

RandomForestClassifier()

In [349]:
y_pred_Rf = Rf.predict(x_test)
y_pred_Rf

array([5336, 3805, 1510, 2432, 3005, 2765, 6392, 4456, 6891,  431, 1406,
       1891, 2935, 7040, 4648, 3348, 5204, 6889, 2134, 2633, 5823, 1098,
       5495, 6536, 1301, 6869, 3846, 7765, 6824, 7132, 1529, 7870, 4826,
       7458, 3761, 4521, 6591, 5305, 3141, 2162,  795, 2689, 7424, 3761,
       4458, 4570, 3368, 3820, 1098, 2689, 4677, 4458, 6855, 7384, 4835,
       4274, 5267, 3659, 6966, 4151, 8395, 1011, 7870, 4744, 7338, 4639,
       4826, 3577, 6118, 3747, 5585, 7605, 3115, 4458, 6572, 5847, 5298,
       6966, 3331, 3214, 5463, 5260, 4905, 3389, 5810, 7429, 5515, 5099,
       5810, 4972,  431, 4968, 5687, 6591, 4835, 2947,  441, 6664, 6290,
       3777, 6230, 5138, 3053, 5260, 3614, 5531, 5424, 8090, 3744, 4097,
       4274, 4835, 4795, 2732,  441, 4182, 4785, 4058, 5424, 6196, 3811,
       6917, 4773, 2402, 4748, 3907, 1891, 6565, 2298, 6192, 1446, 6290,
       1562, 7282, 3784, 6169, 6043, 6273, 5409, 6536, 4660, 6398, 5459,
       5566, 6536, 7132, 5302, 2121, 7429, 4826, 50

In [352]:
Rf_mse = mean_squared_error(y_test,y_pred_Rf)
Rf_mse

2275810.095890411

In [356]:
Rf_r = r2_score(y_test,y_pred_Rf)
Rf_r

0.45750275334296253

In [358]:
Rf_mae = mean_absolute_error(y_test, y_pred_Rf)
Rf_mae

1176.1598173515981

In [ ]:
#스케일링 진행
X = cancer.iloc[:,:-1]
y = cancer.iloc[:,-1]

from sklearn.preprocessing import StandardScaler

# StandarScaler 적용

scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)

# 변환된 X로 데이터 분할
X_train, X_test, y_train, y_test = ms.train_test_split(X_scaled, y, 
                                                      test_size = 0.3, random_state = 100)

import sklearn.svm as svm
import sklearn.metrics as mt
from sklearn.model_selection import cross_val_score, cross_validate

# SVM, kernel = 'linear'로 선형분리 진행
 
svm_clf =svm.SVC(kernel = 'linear', random_state=100)

# 변환된 X로 교차검증

scores = cross_val_score(svm_clf, X_scaled, y, cv = 5)
scores

pd.DataFrame(cross_validate(svm_clf, X_scaled, y, cv =5))

print('교차검증 평균: ', scores.mean())
